# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    # - name: baden
    #   url-base: https://github.com/baden
    # - name: badenwork
    #   # url-base: https://github.com/badenwork
    #   url-base: git@github.com:badenwork

  projects:
    - name: zephyr
      # remote: baden
      remote: zephyrproject-rtos
      # revision: main
      revision: v3.7.0
      # revision: 52fd66b
      # import:
      #   # By using name-allowlist we can clone only the modules that are
      #   # strictly needed by the application.
      #   name-allowlist:
      #     - cmsis      # required by the ARM port
      #     # - hal_nuvoton
    # - name: hal_nuvoton
    #   remote: badenwork
    #   revision: master
    #   path: modules/hal/nuvoton
    # - name: mcuboot
    #   remote: zephyrproject-rtos
    #   revision: 6eca8bbc2bdbf16d5ebbfd89ca27aaa9b3d88400
    #   path: bootloader/mcuboot
